- Jenkinsfile
Added Jenkinsfile to correlate with Quipucords build.
Relates to 
- https://github.com/quipucords/quipucords/pull/1866
- https://github.com/quipucords/quipucords/pull/1867
> chore(build): Jenkinsfile added

- Jenkinsfile
- package.json
- yarn.lock
- Added recommended stages per @himmAllRight 
- Converted to using `yarn` to compile files
- Patched one of the NPM resources, this seemed to allow Jenkins to recognize the package, almost appears as if the `yarn.lock` may have been part of it
- The same CI script setup that runs on Travis, also runs on Jenkins.
And for the future...
- we probably need some form of output checks in place to make sure the correct files are in place. Can create a repo level check and/or a QE level integration check. @himmAllRight 
- Jenkins will need to be used to confirm output, and pass
> chore(build): Jenkinsfile stages, and yarn

- src/components/addSourceWizard/__tests__/__snapshots__/addSourceWizardStepThree.test.js.snap
- src/components/addSourceWizard/addSourceWizardStepThree.js
- src/components/addSourceWizard/addSourceWizardStepTwo.js
- fix(addSourceWizard): copy updates
* copy updates for error handling
1. update the NPM packages with `$ npm install` or `$ yarn`
1. `$ npm test` or `$ yarn test`
1. update the NPM packages with `$ npm install` or `$ yarn`
1. `$ npm run test:dev` or `$ yarn test:dev`
#19
> fix(addSourceWizard): copy updates

- src/components/sources/sourceListItem.js
- fix(sourceListItem): update sources list on delete
* refresh issue on deleting a source
* looks like during some of the support updates for the Add Source Wizard options, and Scan options we overlooked adding these lines back in
1. clone the repo, create a branch, pull the changes from `cdcabrera issues/19-extended` 
1. You'll need to create a source first in order to access the delete dialog, create source, then delete (the source doesn't actually have to be valid for this to be tested). This should …
> fix(sourceListItem): update sources list on delete

- src/common/helpers.js
- src/components/createScanDialog/__tests__/__snapshots__/createScanDialog.test.js.snap
- src/components/createScanDialog/__tests__/createScanDialog.test.js
- src/components/createScanDialog/createScanDialog.js
- src/styles/app/_forms.scss
* fix(createScanDialog, helpers): issues/34 deep scan copy
* createScanDialog, label copy for in-depth scans, unit test
* helpers, getMessageFromResults add requestUrl
1. `$ yarn test:dev`
1. clone the repo, create a branch, pull the changes
1. You'll need to create a source first in order to access the scans dialog
#1 #34
> fix(createScanDialog, helpers): issues/34 deep scan copy

- src/styles/app/_views.scss
* fix(sources view): issues/39 network address styling
1. clone the repo, create a branch, pull the changes
1. `$ yarn start` ... this should run the developer ui alongside random response data.
1. you may have to refresh the view to have it randomly generate a `network` source
1. clone the repo, create a branch, pull the changes …
> fix(sources view): issues/39 network address styling

- templates/registration/logged_out.html
- templates/registration/login.html
- fix(login, logged_out): issues/40 copy
* copy update Django login, out templates
1. clone the repo, create a branch, pull the changes
#40
> fix(login, logged_out): issues/40 copy

- tests/__snapshots__/templates.test.js.snap
- tests/templates.test.js
- feat(build): issues/7 template output tests
* output test for Django base, login & out templates
- ~tests will break when #42 is merged, this PR will need to rebased~
1. `$ yarn build` to emulate Jenkins, then
1. `$ yarn test:integration`
1. all tests should pass... if you wanted to double check the test as "working", change one of the files HTML structure slightly and a diff callout should register
- `./templates/base.html`
- `./templates/registration/login.html`
- `./templates/registration/logged_out.html`
...
#7
> feat(build): issues/7 template output tests

- Jenkinsfile
Removed version from tar.gz ui distribution name
...
...
> Remove version from tar.gz filename

- CHANGELOG.md
- package.json
> chore(build): changelog

- package.json
- yarn.lock
- chore(build): patches for axios, lodash
Ongoing package updates, see Github security alerts
> chore(build): patches for axios, lodash

- CHANGELOG.md
- package.json
- chore(build): changelog, version
- Tag accordingly with `0.9.1` after merge
- Merging dependency on commit/tagging updates from Quipudocs
Ongoing
> chore(build): changelog, version 0.9.1

- package.json
- yarn.lock
Quipudocs package update
...
ongoing
> chore(quipudocs): package update

- Jenkinsfile
> Update Jenkins to produce a tar.gz that reflects the product name

- CHANGELOG.md
- package.json
* **addSourceWizardStepTwo:** issues/77 add source regex ([#78](https://github.com/quipucords/quipucords-ui/issues/78)) ([3d1aeea](https://github.com/quipucords/quipucords-ui/commit/3d1aeea))
* **build:** file lint updates ([2919e90](https://github.com/quipucords/quipucords-ui/commit/2919e90))
* **build:** npm updates and linting ([dc5cbdf](https://github.com/quipucords/quipucords-ui/commit/dc5cbdf))
> chore(build): changelog, version 

- package.json
- yarn.lock
- chore(deps): quipudocs bump
...
> chore(deps): quipudocs bump

- .github/workflows/integration.yml
- package.json
- src/components/aboutModal/__tests__/__snapshots__/aboutModal.test.js.snap
- src/components/aboutModal/aboutModal.js
- tests/version.test.js
- Include a GH Action step to publish assets on release
- Bump package version for 0.10.0 release
contributes to [DISCOVERY-171](https://issues.redhat.com/browse/DISCOVERY-171)
> chore(build): publish assets on release and bump version

- package.json
- src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
- src/components/table/__tests__/__snapshots__/table.test.js.snap
- src/components/table/__tests__/__snapshots__/tableEmpty.test.js.snap
- src/components/table/__tests__/__snapshots__/tableHelpers.test.js.snap
- src/components/table/__tests__/table.test.js
- src/components/table/__tests__/tableEmpty.test.js
- src/components/table/__tests__/tableHelpers.test.js
- src/components/table/table.js
- src/components/table/tableEmpty.js
- src/components/table/tableHelpers.js
- yarn.lock
1. **table** discovery-154 pf4 table wrapper (d9b43c9)
- there are no visual changes associated with this PR
- wrapper for allowing ease of implementation when using pf4 composable table
...
[DISCOVERY-154](https://issues.redhat.com/browse/DISCOVERY-154)
related #106
> feat(table): discovery-154 pf4 table wrapper

- src/components/addSourceWizard/__tests__/__snapshots__/addSourceWizardStepTwo.test.js.snap
- src/components/addSourceWizard/addSourceWizardStepTwo.js
- src/components/createScanDialog/__tests__/__snapshots__/createScanDialog.test.js.snap
- src/components/createScanDialog/createScanDialog.js
- src/components/form/__tests__/__snapshots__/checkbox.test.js.snap
- src/components/form/__tests__/checkbox.test.js
- src/components/form/checkbox.js
- src/styles/app/_patternflyOverrides.scss
Towards #104 : Checkbox component. [Ported from Curiosity](https://github.com/RedHatInsights/curiosity-frontend/blob/main/src/components/form/checkbox.js).
> refactor(checkbox): refactor forms checkbox to use PF4 components

- src/components/createCredentialDialog/__tests__/__snapshots__/createCredentialDialog.test.js.snap
- src/components/createCredentialDialog/createCredentialDialog.js
- src/components/form/formGroup.js
Convert TextInputs to PF4 in Add/Edit credentials dialog. 
Towards #104 : TextInput
> refactor(credentialDialog): convert TextInput fields to PF4

- package.json
- src/components/app.js
- src/components/credentials/__tests__/__snapshots__/credentials.test.js.snap
- src/components/credentials/credentials.js
- src/components/pageLayout/__tests__/__snapshots__/pageLayout.test.js.snap
- src/components/pageLayout/__tests__/pageLayout.test.js
- src/components/pageLayout/pageLayout.js
- src/components/router/__tests__/__snapshots__/router.test.js.snap
- src/components/router/__tests__/__snapshots__/routerConstants.test.js.snap
- src/components/router/router.js
- src/components/router/routerConstants.js
- src/components/scans/__tests__/__snapshots__/scans.test.js.snap
- src/components/scans/__tests__/__snapshots__/scansEmptyState.test.js.snap
- src/components/scans/__tests__/scansEmptyState.test.js
- src/components/scans/scans.js
- src/components/sources/__tests__/__snapshots__/sources.test.js.snap
- src/components/sources/sources.js
- src/redux/index.js
- yarn.lock
- [refactor(router): react router, npm update](https://github.com/quipucords/quipucords-ui/commit/32d95ce2511044f2c6d60970e64967677c712abc)
- upgrades react router so it's no longer dependent on the older NPM package
- squashes a couple of console warnings/errors about attributes handled via pageLayout.js
...
[DISCOVERY-150](https://issues.redhat.com/browse/DISCOVERY-150)
ongoing
related #95
> refactor(router): react router, npm update

- src/components/app.js
- src/components/credentials/__tests__/__snapshots__/credentials.test.js.snap
- src/components/credentials/credentials.js
- src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
- src/components/scans/__tests__/__snapshots__/scanDownload.test.js.snap
- src/components/scans/__tests__/__snapshots__/scanJobsList.test.js.snap
- src/components/scans/__tests__/__snapshots__/scans.test.js.snap
- src/components/scans/__tests__/__snapshots__/scansContext.test.js.snap
- src/components/scans/__tests__/scanDownload.test.js
- src/components/scans/scanDownload.js
- src/components/scans/scanJobsList.js
- src/components/scans/scans.js
- src/components/scans/scansContext.js
- src/components/sources/__tests__/__snapshots__/sources.test.js.snap
- src/components/sources/sources.js
- src/components/toastNotificationsList/__tests__/__snapshots__/toastNotificationsList.test.js.snap
- src/components/toastNotificationsList/__tests__/toastNotificationsList.test.js
- src/components/toastNotificationsList/toastNotificationsList.js
- src/redux/actions/__tests__/reportsActions.test.js
- src/redux/actions/reportsActions.js
- src/redux/reducers/__tests__/__snapshots__/reportsReducer.test.js.snap
- src/redux/reducers/__tests__/__snapshots__/scansReducer.test.js.snap
- src/redux/reducers/__tests__/reportsReducer.test.js
- src/redux/reducers/__tests__/scansReducer.test.js
- src/redux/reducers/reportsReducer.js
- src/redux/reducers/scansReducer.js
- src/redux/selectors/scansSelectors.js
- perf(app): app base to hooks
- fix(credentials,scans,sources): center pending modal
- perf(toastNotificationsList): toasts to hooks
- refactor(scanDownload): class to function, hooks
- corrects
- centering the pending modal icon with text
- toast notifications displaying on download
1. confirm
- the app still renders
- confirm toast notifications display for downloaded scans, and related jobs
- confirm toast notification behavior is maintained
1. confirm build checks come back clean
...
ongoing
> Fixes, performance and consistency updates

- CHANGELOG.md
- CONTRIBUTING.md
- package.json
- yarn.lock
- chore(build): discovery-159 generated changelog
1. `$ yarn release --dry-run`
- confirm the terminal output generates a changelog
1. create a NEW branch and sync it with the upstream/dev 
- then run `$ yarn release`
- confirm a commit is generated with updates to `CHANGELOG.md` and `package.json`
- confirm the commits on `CHANGELOG.md` align with a potential release
- undo the generated commit, or leave it be =) 
...
[DISCOVERY-159](https://issues.redhat.com/browse/DISCOVERY-159)
> chore(build): discovery-159 generated changelog

- .github/workflows/integration.yml
- package.json
- yarn.lock
This is just merging recent commits from the `dev` branch, which is used by `dependabot`, into the `master` branch.
> merge dev into master

- CONTRIBUTING.md
- README.md
- docs(readme,contributing): discovery-330 in-depth workflows
- prep, directions, for bulk NPM updates and general development workflows
1. Review the README.md - https://github.com/cdcabrera/quipucords-ui/blob/dis-330-docs/README.md
2. Review the CONTRIBUTING.md - https://github.com/cdcabrera/quipucords-ui/blob/dis-330-docs/CONTRIBUTING.md
...
[DISCOVERY-330](https://issues.redhat.com/browse/DISCOVERY-330)
dependent on #209 #213
> docs(readme,contributing): discovery-330 in-depth workflows

- CONTRIBUTING.md
- README.md
Proposed release `v1.5.1`
* **readme,contributing** discovery-330 in-depth workflows  ([#214](https://github.com/quipucords/quipucords-ui/pull/214)) ([b68d9ce](https://github.com/quipucords/quipucords-ui/commit/b68d9ce7e67699ecfa5c69e797f9a273458dcdff))
#218 merging first
> Sync, Documentation

- CHANGELOG.md
- package.json
Update version and changelog for 1.6.1
> chore(release): 1.6.1

- src/pages/sources/AddSourceModal.tsx
- src/pages/sources/SourcesListView.tsx
- src/types.ts
add ability to update/edit a source. uses the add source modal.
> feat(Sources): add ability to edit source

- src/pages/sources/AddSourceModal.tsx
- src/pages/sources/SourcesScanModal.tsx
from design meeting with natalie and yichen, we decided to use vertical forms
> chore(Sources): use vertical forms

- src/pages/sources/SourcesListView.tsx
this was probably just a copy/paste mistake
@nicolearagao  - you can do the same to creds
> chore(Sources): add full pagination on bottom of table

- .env.development
- src/common/queryHelpers.ts
- src/pages/scans/ScanActionMenu.tsx
- src/pages/scans/ScansListView.tsx
- src/pages/scans/useScansQuery.ts
- src/pages/sources/SourcesListView.tsx
- src/types.ts
showing basic data, showing most recent connection/status, showing number of sources (and a list if clicked), ability to delete
> feat(Scans): added basic table with some features

- src/common/queryHelpers.ts
> fix(Filters): fixed issue causing filters not to work

- src/app/appLayout/AppToolbar.tsx
- yarn.lock
> feat(Theme): add dark theme option

- CHANGELOG.md
- package.json
Update `CHANGELOG.md` and `package.json` for new release.
Relates to JIRA: DISCOVERY-519
https://issues.redhat.com/browse/DISCOVERY-519
> chore(release): 1.6.2

- src/common/__tests__/helpers.test.ts
- src/common/helpers.ts
- src/components/refreshTimeButton/RefreshTimeButton.tsx
- src/pages/credentials/CredentialsListView.tsx
- src/pages/scans/ScansListView.tsx
- src/pages/sources/SourcesListView.tsx
- src/types.ts
Move utility functions to helpers module, improve error handling, add tests and docstrings.
> refactor: move helper functions from pages

- CHANGELOG.md
- package.json
Update version and changelog for upcoming release.
> chore(release): 1.6.3

- src/pages/scans/ScansListView.tsx
refactor empty state to be more "PF" way, add description and link
> feat(Scans): better empty state screen

- .github/workflows/build.yml
Relates to JIRA: DISCOVERY-627
rename target branch for building UI image
[DISCOVERY-627](https://issues.redhat.com/browse/DISCOVERY-627)
> ci: rename target branch for build

- .github/workflows/commit_lint.yml
- scripts/actions.commit.js
Relates to JIRA: DISCOVERY-630
- ci: ds-630 strict commit subject linting
- applies a parallel requirement (to the appending the issue number to the commit message) for an issue number abbreviation to appear in the commit subject/1st line
- Additional rules around PRs will be following
- Opening a PR without the correct syntax will fail the check
- Syntax should include one of the accepted types
- 'feat',
- 'fix',
- 'docs',
- 'style',
- 'refactor',
- 'perf',
- 'test',
- 'build',
- 'ci',
- 'chore',
- 'revert'
- Syntax should include an abbreviated form of the issue number, for this project `ds-[your issue number]`
- Syntax should include an exact description
- On merging of the PR the PR should include a PR reference in the form of `(#[pr number])`
- The redundancy of adding the PR number …
> ci: ds-630 strict commit subject linting

- src/common/__tests__/helpers.test.ts
- src/components/refreshTimeButton/refreshTimeButton.tsx
- src/components/typeaheadCheckboxes.tsx
- src/hooks/api/useScanApi.ts
- src/pages/credentials/credentialsListView.tsx
- src/pages/scans/components/__tests__/scansModal.test.tsx
- src/pages/scans/components/scansModal.tsx
- src/pages/sources/components/addSourceModal.tsx
- src/types.ts
Relates to JIRA: DISCOVERY-629
- style: ds-629 correct eslint errors
- Fixes errors/warnings raised by the reactivation of webpack eslint
- Running `yarn lint` should accuse neither errors nor warnings
...
[DISCOVERY-629](https://issues.redhat.com/browse/DISCOVERY-629)
> style: ds-629 correct eslint errors

- src/hooks/__tests__/__snapshots__/useAlerts.test.ts.snap
- src/hooks/__tests__/useAlerts.test.ts
- src/hooks/useAlerts.ts
- src/views/credentials/viewCredentialsList.tsx
- src/views/scans/viewScansList.tsx
- src/views/sources/viewSourcesList.tsx
What's included
test: ds-680 add unit tests to hooks module
Notes
Covers useAlerts file
How to test
2. `$ npm test`
2. `$ npm run test:watch`
2. `$ npm run start`
2. `$ npm run build`
Updates issue/story
[DISCOVERY-680](https://issues.redhat.com/browse/DISCOVERY-680)
> test: ds-680 add unit tests to hooks/useAlerts

- .github/workflows/build.yml
- build: ds-627 prepare workflow for main branch
- last of the out-of-sync updates
_Note: unit testing will break on PRs until coverage minimums are met_
...
[DISCOVERY-627](https://issues.redhat.com/browse/DISCOVERY-627)
relates #341
> build: ds-627 prepare workflow for main branch

- package-lock.json
- package.json
- build(deps-dev): bump weldable from 3.1.1 to 3.1.2
1. confirm tests fail as expected
1. `$ npm run build`
1. confirm build comes back clean
...
ongoing
> build(deps-dev): bump weldable from 3.1.1 to 3.1.2

- jest.config.js
- test: ds-742 remove typings, constants from coverage
- typings is still lint/processed/checked by Typescript
- the constants file is a carryover from the original v1 work pre-Typescript. a way to handle enums without access to string enums
- this may, or may not, slightly increase coverage
...
> test: ds-742 remove typings, constants from coverage

- config/jest.setupTests.js
- public/locales/en.json
- src/views/notFound/__tests__/__snapshots__/notFound.test.tsx.snap
- src/views/notFound/__tests__/notFound.test.tsx
- src/views/notFound/notFound.tsx
- refactor(notFound): ds-742 test, simplify, add translation
1. `$ npm start`
1. confirm the `notFound` view displays as intended by navigating to a non-existent route
...
> refactor(notFound): ds-742 test, simplify, add translation

- src/components/actionMenu/__tests__/__snapshots__/actionMenu.test.tsx.snap
- src/components/actionMenu/__tests__/actionMenu.test.tsx
- src/components/actionMenu/actionMenu.tsx
- test(actionMenu): ds-742 lint, test updates
- this should squash errors as warnings being broadcast in the test console regarding `act`
- the simplified tests produce close to the same coverage results
...
> test(actionMenu): ds-742 lint, test updates

- src/components/typeAheadCheckboxes/__tests__/__snapshots__/typeaheadCheckboxes.test.tsx.snap
- src/components/typeAheadCheckboxes/__tests__/typeaheadCheckboxes.test.tsx
- src/components/typeAheadCheckboxes/typeaheadCheckboxes.tsx
- test(typeaheadCheckboxes): ds-742 lint, basic test
- applies basic code style and test
- this component needs to be broken out into testable pieces, using a function component to emulate class like segmentation is difficult to read
...
> test(typeaheadCheckboxes): ds-742 lint, basic test

- src/hooks/useScanApi.ts
- src/types/types.ts
- src/views/sources/__tests__/__snapshots__/showSourceConnectionsModal.test.tsx.snap
- src/views/sources/__tests__/showSourceConnectionsModal.test.tsx
- src/views/sources/showSourceConnectionsModal.tsx
- src/views/sources/viewSourcesList.tsx
- test(showSourceConnectionsModal): ds-742 lint, add tests
- add missing test
- adjust `Connections` type to highlight we only use name
- adjust the component name to reflect file
...
> test(showSourceConnectionsModal): ds-742 lint, add tests

- jest.config.js
- test: ds-767 ignore views from coverage
- the current view components' formats are a carry over from the initial v2 rewrite.
- They have been minimally refactored to move the project forward. 
- Their architecture falls outside of, the now, normal unit testing workflow, and is better tested with e2e since they wrap large sections of code that is technically unit tested.
- In the future these views should be broken apart more, both for component updating, and unit testing
1. confirm the `view` components are skipped for coverage checks
...
[DISCOVERY-767](https://issues.redhat.com/browse/DISCOVERY-767)
> test: ds-767 ignore views from coverage

- src/views/sources/__tests__/__snapshots__/addSourcesScanModal.test.tsx.snap
- src/views/sources/__tests__/addSourcesScanModal.test.tsx
- src/views/sources/addSourcesScanModal.tsx
- src/views/sources/viewSourcesList.tsx
- test(addSourcesScanModal): ds-767 lint, test updates
- minor component clean up
- basic unit testing added
1. `$ npm run start:stage`
1. confirm adding a scan still behaves as intended
1. `$ npm run build`
1. confirm output comes back passing
...
[DISCOVERY-767](https://issues.redhat.com/browse/DISCOVERY-767)
> test(addSourcesScanModal): ds-767 lint, test updates

- Jenkinsfile
Thanks to that file and changes to internal Jenkins configuration, we will have end to end tests from Camayoc running against each PR in this repo.
> test: ds-523 introduce Camayoc PR testing

- .github/workflows/build.yml
- Adding ARM64 architecture to the quipucords-ui container image.
- Now creating the quipucords-ui container as the multi-arch manifest so it can be pulled from wither x86_64 or arm64
> Adding support for ARM64

- .github/workflows/build.yml
- Fixed issue where merges were not creating the latest-<ARCH> tags but the main-<ARCH> named ones.
> Fixed issue where merges were incorrectly creating the latest image

- .github/workflows/build.yml
- When creating x.y.z releases, was missing the x.y container image manifest.
> build: Missing x.y release container image
