src/components/createScanDialog/__tests__/__snapshots__/createScanDialog.test.js.snap, src/components/createScanDialog/createScanDialog.js
* fix(createScanDialog): issues/28 concurrency default
* update concurrency default from 50 to 25
* the UI can really set any concurrency default it wants based on the current implementation. In this case however we're aligning the default defined by the API
1. update the NPM packages with `$ yarn` then
1. update the NPM packages with `$ yarn` then
1. `$ yarn test:dev`
1. clone the repo, create a branch, pull the changes from `cdcabrera issues/28` 
1. You'll need to create a source first in …
=> fix(createScanDialog): issues/28 concurrency default

scripts/version.sh, tests/version.test.js
- fix(build): issues/29 version display
* display version on creation
* integration test for version
* the unit test checks the format `[string]=[number].[number].[number].[7 character hash]`
1. `$ yarn test:integration`
1. run `$ yarn build:version`
Running `$ yarn build:version` should produce output similar to...
#29
=> fix(build): issues/29 version display

scripts/api.sh
- fix(build): issues/50 clean up docker review env
- This is an iteration, where first round we're opting to fix/update the normal build script we use to create the GUI `review` environment
You'll need to run the review environment start script multiple times to see this update actually function. Once it activates you'll see some additions to the console log around Docker clean itself up
1. sync these updates with your fork then
1. `$ yarn start:review`
1. the first time you run this the clean up may not happen, the second time you run it you'll either see a log message with the following in it (takes a bit...)
```
[api:review] 
[api:review] Cloning QPC...
[api:review] Untagged: qpc-review:latest
[api:review] Deleted: sha256:8713790fb7b...
```
or just 
```
[api:review] 
[api:review] …
```
=> fix(build): issues/50 clean up docker review env

src/common/__tests__/__snapshots__/helpers.test.js.snap, src/common/helpers.js, src/services/reportsService.js
- fix(reportsService): issues/52 name report package download
* reportsService, move to axios, add responseType
* helpers, remove downloadPackage in favor of downloadData
- This corrects the naming issue around the report by adding in the `tar.gz`. The current package download generates the name based on the browser, which can be confusing... Chrome labels it `download.gz` and Firefox labels it `[some hash].gz`. To round it out the file doesn't open on RHEL without the `tar` in there, this fix corrects all of that.
The Dev UI can be used for a quick confirmation on **just the file name** coming through. Trying to unzip it will create an infinite loop of annoyance since the `tar.gz` isn't legit.
1. update the NPM packages with `$ …
=> fix(reportsService): issues/52 name report package download

scripts/quipudocs.js, src/components/pageLayout/__tests__/__snapshots__/pageLayout.test.js.snap, src/components/pageLayout/pageLayout.js, tests/brand.test.js
Disables the menu item for Install guide
- fix(quipudocs, pageLayout): issues/68 disable install guide
1. make sure Docker is running
1. `$ yarn start:review`
1. Confirm the menus still function at both desktop and smaller screen sizes, see below examples
Closes #68
=> fix(quipudocs, pageLayout): issues/68 disable install guide

CHANGELOG.md, package.json
- chore(build): changelog, version
- Tag accordingly with `0.9.2` after merge
- There is a development dependency on commit/tagging updates from Quipudocs. However, the packaging build that leverages Jenkins will pull the latest Quipudocs
Ongoing
=> chore(build): changelog, version

package.json, scripts/clean.sh, scripts/post.sh
- chore(build): post clean up, remove unused css copy
- applies the cleanup convenience script to the build npm script to help with local development
- `$ yarn build:clean`
1. confirm the extra files that normally hang around in the "./public" directory no longer exist
...
[DISCOVERY-8](https://issues.redhat.com/browse/DISCOVERY-8)
=> chore(build): post clean up, remove unused css copy

.eslintrc, package.json, scripts/quipudocs.js, src/common/helpers.js, src/components/aboutModal/__tests__/__snapshots__/aboutModal.test.js.snap, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/i18n/__tests__/__snapshots__/i18nHelpers.test.js.snap, src/components/i18n/__tests__/i18n.test.js, src/components/i18n/__tests__/i18nHelpers.test.js, src/components/i18n/i18n.js, src/components/i18n/i18nHelpers.js, src/setupTests.js, tests/__snapshots__/code.test.js.snap, yarn.lock
1. **build** discovery-8 allow repo locale files (dcc369a)
- Locale strings factors into the PF4 updates. We had considered delaying this set of updates until after PF4, but opted to apply it before/during to avoid additional cycles if/when string additions start popping up
- we would have preferred to apply strings as `en-US.json` but for now we'll update as `en.json` and test out `en.json` as the fallback language
- Allows the repo to apply locale strings in addition to the existing process of pulling locale strings from the Quipudocs repo.
- Quipudocs locale strings will always take priority over repo level locale strings
1. edit AND commit temporarily an update to the `./public/locales/en.json` file
1. run the build
1. confirm …
=> fix(build): discovery-8 allow repo locale files

.eslintrc, public/locales/en.json, src/common/helpers.js, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/modal/__tests__/__snapshots__/modal.test.js.snap, src/components/modal/__tests__/modal.test.js, src/components/modal/modal.js, src/components/router/routerConstants.js, src/redux/selectors/credentialsSelectors.js, src/redux/selectors/scansSelectors.js, src/redux/selectors/sourcesSelectors.js, src/services/config.js, src/services/userService.js, src/styles/app/_modal.scss, src/styles/index.scss
1. **build** activate eslint jsdoc (9c3aa91)
1. **pf4-style** expose scss variables (e402a77)
1. **modal** discovery-149 pf4 modal wrapper (1feaa58)
- Build updates
- SCSS variables applied
- Modal wrapper created for future modal needs, see #88 
- **There are NO visual/design updates associated with this request**
1. confirm the build completes without error
...
[DISCOVERY-149](https://issues.redhat.com/browse/DISCOVERY-149)
related #88
=> feat(modal): discovery-149 pf4 modal wrapper

src/components/createCredentialDialog/createCredentialDialog.js
...
Converts the instance of `Alert` in createCredentialDialog.js to use new PF4 component/styling.
Towards #91 
1. Change line 389 of https://github.com/quipucords/quipucords-ui/compare/dev...jenny-s51:credentialDialogConvertAlert?expand=1#diff-c9e674b4dc402e05f627561a03fa45b3e001693235edd669a9df547cb160522bL387 to `if (!error) {`
2. Go to Credentials -> Add and click on each type 
...
Before:
After:
https://issues.redhat.com/browse/DISCOVERY-148
=> refactor(Alert): convert alert to PF4 in credential dialog

public/locales/en.json, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/refreshTimeButton/__tests__/__snapshots__/refreshTimeButton.test.js.snap, src/components/refreshTimeButton/refreshTimeButton.js, src/components/viewToolbar/__tests__/__snapshots__/viewToolbar.test.js.snap
Closes #102
Refactoring `refreshTimeButton.js` to PF4 component/styling
Styling issue. PF-react-core `Button` with `variant="link"` makes button blue. Also, old icon used is font-awesome refresh. However, PF icons does not have refresh so `RebootingIcon` was used. Additionally, there's an alignment styling issue.
Before:
After:
https://issues.redhat.com/browse/DISCOVERY-148
=> refactor(refreshTimeButton): pf4 refreshTimeButton component

public/locales/en.json, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/scans/__tests__/__snapshots__/scansEmptyState.test.js.snap, src/components/sources/__tests__/__snapshots__/sources.test.js.snap, src/components/sources/__tests__/__snapshots__/sourcesEmptyState.test.js.snap, src/components/sources/__tests__/sourcesEmptyState.test.js, src/components/sources/sources.js, src/components/sources/sourcesEmptyState.js
1. **sources** discovery-148 pf4 empty-state
1. navigate to the sources view, with zero sources the initial welcome message should display
1. next add a source, then filter it so NO sources display, and confirm the empty state filter with magnifying glass displays
1. recreating the error we handled by modifying the Redux state layer... open the `./src/components/sources/sources.js` file and add the two lines for `, error: true, errorMessage: 'Lorem ipsum'`
```
const mapStateToProps = state => ({
...state.sources.view,
viewOptions: state.viewOptions[reduxTypes.view.SOURCES_VIEW],
error: true,
errorMessage: 'Lorem ipsum'
});
```
[DISCOVERY-148](https://issues.redhat.com/browse/DISCOVERY-148)
#99
=> refactor(sources): discovery-148 pf4 empty-state

src/components/sources/__tests__/__snapshots__/sourceListItem.test.js.snap, src/components/sources/__tests__/__snapshots__/sources.test.js.snap, src/components/sources/sourceListItem.js, src/components/sources/sources.js, src/styles/app/_views.scss
Towards #134, ~closes #135~
**Before:**
**After:**
=> refactor(buttons): convert buttons on Sources screen to PF4

src/components/credentials/__tests__/__snapshots__/credentialsListItem.test.js.snap, src/components/credentials/credentialListItem.js, src/components/scans/__tests__/__snapshots__/scanListItem.test.js.snap, src/components/scans/__tests__/__snapshots__/scans.test.js.snap, src/components/scans/scanListItem.js, src/components/scans/scans.js
...
Converts PF3 buttons to PF4 buttons in list view of Scans and Credentials screens. 
**This includes the icons on the right of every list item, and the "Merge Reports" button on the Scans screen.**
**The changes in this PR are aligned with the code and feedback in #136** 
...
[DISCOVERY-149](https://issues.redhat.com/browse/DISCOVERY-149)
#134
=> refactor(buttons): convert buttons in scans and credentials list views

src/components/createScanDialog/__tests__/__snapshots__/createScanDialog.test.js.snap, src/components/createScanDialog/__tests__/createScanDialog.test.js, src/components/createScanDialog/createScanDialog.js
...
Closes https://github.com/quipucords/quipucords-ui/issues/91; converts instance of createScanDialog `Alert` to PF4.
Extends and follows code style of https://github.com/quipucords/quipucords-ui/pull/108/files.
Also updated [createScanDialog.test.js](https://github.com/quipucords/quipucords-ui/compare/dev...jenny-s51:createScanDialog_alert?expand=1#diff-2226e7fecf59cdb8c1ea3ac7e3b60b26ec20a3048d4ebf9567872514c54e9d19) to get the new PF4 alert by its updated classname.
...
=> refactor(Alert): convert alert in Create Scan Dialog to PF4

src/components/dropdownSelect/__tests__/__snapshots__/dropdownSelect.test.js.snap, src/components/dropdownSelect/__tests__/dropdownSelect.test.js, src/components/dropdownSelect/dropdownSelect.js, src/components/form/__tests__/__snapshots__/formHelpers.test.js.snap, src/components/form/__tests__/__snapshots__/textInput.test.js.snap, src/components/form/__tests__/formHelpers.test.js, src/components/form/__tests__/textInput.test.js, src/components/form/formHelpers.js, src/components/form/textInput.js
1. **textInput,formHelpers** discovery-151 pf4 text input
1. **dropdownSelect** discovery-151 undefined options
- extracted from the toolbar work
- prep for form updates to pf4
1. confirm interaction with existing dropdownSelect fields remains unchanged
...
[DISCOVERY-151](https://issues.redhat.com/browse/DISCOVERY-151)
[DISCOVERY-153](https://issues.redhat.com/browse/DISCOVERY-153)
#104
=> feat(textInput,formHelpers): discovery-151 pf4 text input

src/components/poll/poll.js, src/components/scans/scanDownload.js
required:
we need to move `poll.js` and `scanDownload.js` into their own PR pointed at the `dev` branch
reason:
because we're doing feature branching with `forms` and the related fields as a standalone aspect we have to be diligent in trying to avoid potential merge conflicts, and focused on the feature itself, forms. Both `poll.js` and `scanDownload.js` are  outside of that feature scope and can be updated on the primary development branch. Additionally, `poll.js` is most likely going to be removed in the future ... part of the `scans` table refactors
_Originally posted by @cdcabrera in https://github.com/quipucords/quipucords-ui/pull/150#discussion_r963758310_
=> cleanup(proptypes): remove propTypes.string where propTypes.node is used

src/components/addSourceWizard/__tests__/__snapshots__/addSourceWizardStepTwo.test.js.snap, src/components/addSourceWizard/addSourceWizardStepTwo.js, src/components/form/__tests__/__snapshots__/textInput.test.js.snap, src/components/form/__tests__/textInput.test.js, src/components/form/textInput.js
Towards #104 : TextInput - extends #149, #150 
Converts remaining PF3 Form Fields in `addSourceWizard`
=> cleanup(sourceWizard): convert text input fields to use PF4 component

src/components/contextIcon/__tests__/__snapshots__/contextIcon.test.js.snap, src/components/contextIcon/contextIcon.js, src/components/createScanDialog/__tests__/__snapshots__/createScanDialog.test.js.snap, src/components/createScanDialog/__tests__/createScanDialog.test.js, src/components/createScanDialog/createScanDialog.js, src/components/mergeReportsDialog/__tests__/__snapshots__/mergeReportsDialog.test.js.snap, src/components/mergeReportsDialog/mergeReportsDialog.js, src/components/pageLayout/__tests__/__snapshots__/pageLayout.test.js.snap, src/components/pageLayout/pageLayout.js, src/components/scans/__tests__/__snapshots__/scanDownload.test.js.snap, src/components/scans/__tests__/__snapshots__/scanJobsList.test.js.snap, src/components/scans/scanDownload.js, src/components/scans/scanJobsList.js, src/components/tooltip/tooltip.js
- refactor(button,icon,spinner): discovery-149 pf4 replacements
- clean up for the last remaining button, icon, and spinners outside of `pageLayout`
- starts to align modal dialogs across
- `add source wizard`
- `create scan dialog`
- `merge reports dialog`
- these updates highlight the inconsistency in our modal/dialog implementations.
- `add source wizard`
- shows both the `x` closing button and close button while pending
- `create scan dialog`
- shows the `x` closing button while pending
- `merge reports dialog`
- shows the closing button while pending
- the remaining modal/dialog has variations in behavior that need to be brought into alignment
- `create credential dialog` 
- does not have a pending message, 
- shuts down immediately after submission
- uses its own internal form state …
=> refactor(button,icon,spinner): discovery-149 pf4 replacements

src/components/sources/sources.js
- fix(sources): discovery-154, activate scans button
- makes it so 2 or more selections activate the scan button in the upper right toolbar, currently it's set for 1 or more
- makes it consistent with the merge reports dialog on scans, and the credentials toolbar delete button 
1. navigate to sources and confirm it now takes 2 or more selections to activate the toolbar `scans` button
[DISCOVERY-154](https://issues.redhat.com/browse/DISCOVERY-154)
=> fix(sources): discovery-154, activate scans button

templates/registration/logged_out.html, templates/registration/login.html, tests/__snapshots__/templates.test.js.snap
For some reason quipucords server is able to find staticfiles under `/assets` in development mode, but not in production mode.
Related to DISCOVERY-189.
Altered the path for staticfiles on django templates
It's impossible to log in with DEBUG mode disabled without these changes (quipucords/quipucords#2194)
On quipucords (server - version proposed on quipucords/quipucords#2194), run
1. `make build-ui`
2. `./quipucords/manage.py collectstatic --settings quipucords.settings --no-input`
3. Run the container with /app mapped to quipucords folder with DJANGO_DEBUG env var set to false
4. Open the GUI in a browser. UI elements should be loaded and login/logout should work.
5. Repeat step 3 with DJANGO_DEBUG env var set to true, then repeat step 4
... …
=> fix(server): discovery-198 replace assets paths

src/components/addSourceWizard/__tests__/__snapshots__/addSourceWizardStepTwo.test.js.snap, src/components/addSourceWizard/addSourceWizardStepTwo.js
Change the default option for Source/optionSslCert to `true`.
[DISCOVERY-178](https://issues.redhat.com/browse/DISCOVERY-178)
=> fix(SourceWizard): discovery-178 sslCert default option

.github/workflows/commit_lint.yml, .github/workflows/integration.yml, README.md, package.json
- chore(build): nodejs 14 to 16
- wrap up task for the 2022 refactors from Nov/Dec
- looks like there are issues with moving to NodeJS 18, so skipping those checks for now until the build gets updated... aka we either migrate to the next React Scripts, or straight Webpack (which might actually be easier now)
1. confirm the interface engine on package.json enforces the NodeJS 16 version check
1. confirm the build completes 
...
[DISCOVERY-110](https://issues.redhat.com/browse/DISCOVERY-110)
Ongoing
=> chore(build): nodejs 14 to 16

CONTRIBUTING.md
Just adding a small suggestion for anyone who might encounter a `ERR_OSSL_EVP_UNSUPPORTED` error when trying to run `yarn start`.
It looks like my editor also automatically stripped some trailing whitespace from a few lines in the `.md` file. Sorry about that!
=> docs(CONTRIBUTING.md): suggest workaround for ERR_OSSL_EVP_UNSUPPORTED

src/components/addSourceWizard/__tests__/__snapshots__/addSourceWizardStepOne.test.js.snap, src/components/addSourceWizard/__tests__/__snapshots__/addSourceWizardStepTwo.test.js.snap, src/components/addSourceWizard/addSourceWizardStepTwo.js, src/components/createScanDialog/__tests__/__snapshots__/createScanDialog.test.js.snap, src/components/form/__tests__/__snapshots__/formGroup.test.js.snap, src/components/form/formGroup.js
- fix(formGroup): discovery-330 pf id to fieldId
- moves from using `id` to `fieldId` attribute for formGroup component
- patches formGroup to apply labels dynamically for known child components
- still the existing issue of not correctly applying labels when used against dropdownSelect 
1. confirm tests come back without error
1. confirm form fields still have a "label" (or span/div in some cases) that displays copy next to a form field
- this will not work against the Dropdown/Select component, this is expected and maintains existing behavior
1. confirm tests come back without error
... …
=> fix(formGroup): discovery-330 pf id to fieldId

config/jest.setupTests.js, src/components/scans/__tests__/scansContext.test.js
- refactor(testing): react testing, handler context wrappers
- expands the React testing Jest handlers to include context in the returned results
...
ongoing
=> refactor(testing): react testing, handler context wrappers

config/jest.setupTests.js
- refactor(testing): jest, pass act, avoid readonly props
- expands the jest handlers and passes `act` back in the event an unknown or `read only` property is encountered apply the instance context convenience methods 
...
ongoing 
related to https://github.com/RedHatInsights/curiosity-frontend/pull/1144
=> refactor(testing): jest, pass act, avoid readonly props

src/components/scans/__tests__/__snapshots__/scans.test.js.snap, src/components/scans/scans.js
The functionality has been broken for a while in the UI, and needs to be updated to leverage the async version of the API. For now we won't expose the Merge report Button and leave this as a CLI only functionality until the UI can be properly updated.
Current feature:
After the disabling the feature (Merge reports button is hidden):
=> chore(refact): Disable the scan Merge Reports functionality.

CONTRIBUTING.md
* update CONTRIBUTING instructions for releasing a new version
* update CONTRIBUTING instructions to stop recommending the "dev" branch
My text editor also automatically fixed some Markdown syntax and spacing issues elsewhere in the document. That's why the dotenv definitions table updated; there are no other meaningful changes to it.
=> update CONTRIBUTING docs

src/pages/sources/SourcesListView.tsx
time ago was always showing 6 hours. moment was being used incorrectly. fixed that.
=> fix(sources): connections were all showing 6hr ago, fixed

src/pages/sources/SourcesListView.tsx
fixed sources table to properly filter by connection and type.
turned off sorting by credential (future story if backend implements sorting by number of credentials)
=> fix(sources): fix sorting by connection and type

src/pages/sources/SourcesListView.tsx
this came out of a discussion with natalie wong. the reason being that refresh button can change size as the text changes, which makes the other two buttons jump around when it exists on the left side.
=> fix(sources): place reset button on right side of others

package.json, src/common/queryHelpers.ts, src/pages/credentials/CredentialsListView.tsx, src/pages/credentials/useCredentialsQuery.ts, src/pages/sources/SourcesListView.tsx, src/pages/sources/useSourcesQuery.ts, yarn.lock
The 1.0.3 version of `@mturley-latest/react-table-batteries` includes breaking changes to get it close to the final API that will be present when it moves to PatternFly. This PR upgrades and changes the usage here to match. It also factors out `queryHelpers.ts` to prevent some repetitive code. We wrap the `useQuery` calls in custom hooks that rely on `tableState.cacheKey` to invalidate the cache rather than a `useEffect`.
cc @gitdallas
=> chore(deps): Upgrade react-table-batteries to 1.0.3 and fix usage

src/common/queryHelpers.ts
there was a typo in the page size portion of the url querystring.
this fix is applied to a common helper, so it will apply to creds/scans as well.
=> fix(Tables): pagination will now be able to change page size

src/pages/sources/SourcesListView.tsx
previously several items were incorrectly wrapped in a single toolbaritem.
likely need similar fix in creds, @nicolearagao
=> chore(Sources): fix spacing for toolbar buttons

src/pages/credentials/CredentialsListView.tsx
This came out of a discussion with natalie wong. The reason being that refresh button can change size as the text changes, which makes the other two buttons jump around when it exists on the left side
=> Fix refresh button positioning for Credentials

src/pages/credentials/CredentialsListView.tsx
previously several items were incorrectly wrapped in a single toolbaritem.
=> chore(creds): fix spacing for toolbar buttons

.github/workflows/yarn_audit.yml
This adds a GitHub workflow to run `yarn audit` to check if dependencies have critical vulnerabilities.
=> chore: add 'yarn audit' GitHub workflow

.github/workflows/integration.yml, .github/workflows/yarn_audit.yml
This change ports the update introduced by https://github.com/quipucords/quipucords-ui/pull/308 from `main` to `v2-rewrite`.
Bumps [actions/cache](https://github.com/actions/cache) from 3 to 4.
- [Release notes](https://github.com/actions/cache/releases)
- [Changelog](https://github.com/actions/cache/blob/main/RELEASES.md)
- [Commits](https://github.com/actions/cache/compare/v3...v4)
---
updated-dependencies:
- dependency-name: actions/cache dependency-type: direct:production update-type: version-update:semver-major ...
=> chore(deps): bump actions/cache from 3 to 4

.dockerignore, .gitignore, deploy/entrypoint.sh, deploy/nginx.conf
Content is now served over https.
Also alow users to provide their own certificates when using a folder mounted to /opt/app-root/certs/.
Otherwise, certificates are generated on-the-fly to avoid the
anti-pattern currently in use in Quipucords server codebase 
(DISCOVERY-361).
...
```
podman build -t qpc-ui .
podman run -it -p 8080:8080 --replace --name qpc-ui qpc-ui
```
head to https://localhost:8080. content should now be served over https.
to test passing customer provided certificates, add ` -v <path/to/certs>:/opt/app-root/certs:z` to
`podman run` command.
[DISCOVERY-536](https://issues.redhat.com/browse/DISCOVERY-536)
=> [DISCOVERY-536] - Serve content over https

config/webpack.dev.js, package.json, yarn.lock
- build: ds-626 reactivate eslint for webpack
- reactivates eslint on webpack startup for both "terminal" and "browser console" output
1. `$ yarn start`
1. you should see something similar to the following message.
- all notifications are non-blocking beyond glaring notification
- development can still continue
- all fixes will be handle in subsequent Jira/stories/issues
[DISCOVERY-626](https://issues.redhat.com/browse/DISCOVERY-626)
=> build: ds-626 reactivate eslint for webpack

package.json, src/components/i18n/i18n.js, yarn.lock
- build(deps): ds-661 move to i18next-http-backend
- moves from the deprecated i18next support package to the newer version
1. `$ yarn start`
1. confirm the `EN` locale is loading... does copy display
- if copy doesn't load this update is broken...
...
[DISCOVERY-661](https://issues.redhat.com/browse/DISCOVERY-661)
blocked by #349
=> build(deps): ds-661 move to i18next-http-backend

src/components/scans/__tests__/__snapshots__/scans.test.js.snap, src/components/scans/__tests__/__snapshots__/scansTableCells.test.js.snap, src/components/scans/scanSourceList.js, src/components/scans/scans.js, src/components/scans/scansTableCells.js
- fix(scans): ds-98 disable expandable sources
- the sources displayed under scans suffers from an sequential id issue, this bypasses the issue by disabling the expansion field
- we discussed using the same display v2 uses but until it can be determined v2 is pulling the correct information we're taking the direct approach of disabling the field all together 
- the number of sources that are displayed is an aspect of what v2 uses to show sources
-  we deprecated the old "scanSourceList.js" component as opposed to deleting it simply because it was faster to type the word vs deleting the file, test file, test snapshots, etc. if someone wants us to remove it entirely we can also do that
1. confirm that the sources displayed on …
=> fix(scans): ds-98 disable expandable sources

src/components/createCredentialDialog/createCredentialDialog.js, src/services/credentialsService.js
- fix(credentials): ds-205 disable edit for encrypted fields
- Moves the credential "update" service from `put` to `patch`
- We opted for the most simplistic solution on this one... 
- Technically the all asterisk values are still returning from the API as before, it's just NOW, before submission of the updated cred the values are removed
- Disables edits for the following encrypted fields. If additional fields are required we can add them in...
- auth_token
- ssh_passphrase
- become_password
- password 
1. make sure `podman` is running
1. add a credential with an encrypted field type
- after adding the credential, edit it, submit it and confirm the field has NOT been updated with `*`asterisk characters . You will most …
=> fix(credentials): ds-205 disable edit for encrypted fields

src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap, src/components/viewToolbar/__tests__/__snapshots__/viewToolbarSelect.test.js.snap, src/components/viewToolbar/viewToolbarSelect.js
Credential type and Source type filter items were missing RHACS and Ansible. We must have forgot to add them back when we introduced these source types. Add these items now.
Relates to JIRA: DISCOVERY-682
=> fix(viewToolbar): dsc-682 add missing types to filter

src/components/createCredentialDialog/__tests__/__snapshots__/createCredentialDialog.test.js.snap, src/components/createCredentialDialog/__tests__/createCredentialDialog.test.js, src/components/createCredentialDialog/createCredentialDialog.js, src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
Don't display "Token" authentication type for Network credential. Not only it doesn't make any sense, such credential can't be created anyway.
Relates to JIRA: DISCOVERY-681
=> fix(credentials): ds-681 hide token in network

.github/dependabot.yml, CONTRIBUTING.md
- ci: ds-652 dependabot groups for bulk updates
- adjust dependabot. technically this will still fire against main, considerations for v2 work becoming `main` may need to happen
...
[DISCOVERY-652](https://issues.redhat.com/browse/DISCOVERY-652) 
related  [DISCOVERY-661](https://issues.redhat.com/browse/DISCOVERY-661)
=> ci: ds-652 dependabot groups for bulk updates

.github/workflows/build.yml, .github/workflows/commit_lint.yml, .github/workflows/integration.yml, .github/workflows/package_audit.yml
- ci: ds-647 adjust gh workflow job names
- we had attempted to align the gh workflow job names so they were consistent unfortunately we highlighted that this causes issues with GH actions itself... apparently someone may be using them as identifiers internally causing issues across multiple facets of the `Checks`  =(
- Confirm that all checks are running
- Commit lint
- Integration testing 20.x, 18.x
- Build Container Image
- NPM Audit
...
[DISCOVERY-647](https://issues.redhat.com/browse/DISCOVERY-647)
=> ci: ds-647 adjust gh workflow job names

config/jest.setupTests.js, src/hooks/__tests__/__snapshots__/useCredentialApi.test.ts.snap, src/hooks/__tests__/__snapshots__/useScanApi.test.ts.snap, src/hooks/__tests__/__snapshots__/useSourceApi.test.ts.snap
- test: ds-356 adjust mock i18next to output string
- needed to avoid TS throwing a type string error when we start testing components. Coincidentally, this starts to revert it back towards the parallel v1.8 version
1. confirm tests come back as expected, some failures, missing marks for coverage
1. `$ npm run build`
1. confirm tests come clean
...
[DISCOVERY-356](https://issues.redhat.com/browse/DISCOVERY-356)
relates #420
=> test: ds-356 adjust mock i18next to output string

src/helpers/__tests__/__snapshots__/helpers.test.ts.snap, src/helpers/__tests__/helpers.test.ts
- test(helpers): ds-742 snapshot, update link click error
- this removes a warning blasted out as an error, because the framework appears to use console.error indiscriminately, from the testing framework due to a missing jsdom ref
...
=> test(helpers): ds-742 snapshot, update link click error

src/components/simpleDropdown/__tests__/__snapshots__/simpleDropdown.test.tsx.snap, src/components/simpleDropdown/__tests__/simpleDropdown.test.tsx, src/components/simpleDropdown/simpleDropdown.tsx, src/views/credentials/__tests__/__snapshots__/addCredentialModal.test.tsx.snap, src/views/credentials/addCredentialModal.tsx, src/views/credentials/viewCredentialsList.tsx, src/views/sources/addSourceModal.tsx, src/views/sources/viewSourcesList.tsx, tests/__snapshots__/code.test.ts.snap
- refactor(simpleDropdown): ds-742 simplify props, test updates
- extends simpledropdown so you no longer have to drop a list of components as options
- squash the act warnings that were popping up in the test framework for this component
1. confirm the simple dropdown component displays as expected in
- viewSourcesList.tsx in the toolbar, "add a source"
- viewCredentialsList.tsx in the toolbar, "add a cred"
- and addSourceModal add a "Connection type"
...
=> refactor(simpleDropdown): ds-742 simplify props, test updates

src/views/credentials/__tests__/__snapshots__/addCredentialModal.test.tsx.snap, src/views/credentials/__tests__/addCredentialModal.test.tsx, src/views/credentials/addCredentialModal.tsx
- fix: ds-391 render correct fields to add-cred network
- fix addCredentialModal test for openshift auth type options
- fix correct field rendering for addCredentialModal, network source type 
...
[DISCOVERY-391](https://issues.redhat.com/browse/DISCOVERY-391)
=> fix: ds-391 render correct fields to add-cred network

deploy/entrypoint.sh, deploy/nginx.conf
Relates to JIRA: DISCOVERY-356
Actually serve the new login UI from the UI container. Stop serving any of the old login UI or old UI in general.
- build the container image (`make build-container`) and tag it appropriately.
- set your new container image name/tag in an installer overrides file. For example…
```
cat ~/.config/quipucords-installer-overrides/quipucords-app.container
[Container]
Image=localhost/quipucords-ui:latest
```
- run the installer with your overrides directory, and start the containers. For example…
```
quipucords-installer --override-conf-dir ~/.config/quipucords-installer-overrides install
systemctl --user start quipucords-app
```
- go to https://localhost:9443 in your browser
- observe all new UI.
https://issues.redhat.com/browse/DISCOVERY-356
=> feat: exclusively serve the current "new" UI

src/views/credentials/__tests__/__snapshots__/addCredentialModal.test.tsx.snap, src/views/credentials/addCredentialModal.tsx
fix(credentials): ds-391 SSH key placeholder text
- Enhance placeholder of SSH key field and add helper text to clarify things for user
...
[DISCOVERY-391](https://issues.redhat.com/browse/DISCOVERY-391)
=> fix(credentials): ds-391 SSH key placeholder text

deploy/entrypoint.sh
This enables a user to start a working container with just:
podman run -p 9443:9443 quipucords-ui:latest
Previously the QUIPUCORDS_APP_PORT environment variable was required, and nginx would fail to start and present a very non-obvious error indicating its absence.
```sh
podman build -t quipucords-ui:latest .
podman run -p 9443:9443 quipucords-ui:latest
```
=> feat: ds-356 run the container without setting QUIPUCORDS_APP_PORT

src/views/credentials/__tests__/__snapshots__/addCredentialModal.test.tsx.snap, src/views/credentials/__tests__/addCredentialModal.test.tsx, src/views/credentials/addCredentialModal.tsx
When choosing auth type username and password, some extra fields should only be generated to network source type.
Relates to JIRA: DISCOVERY-391
- fix to "[Mirek] Satellite / vCenter / Ansible new credential form have fields for Become Method, Become User and Become Password. I have not tried if they are also available in edit credential form, and I have not verified what happens when you fill them and submit credential to backend"
[DISCOVERY-391](https://issues.redhat.com/browse/DISCOVERY-391)
=> fix(credential): ds-391 correct rendered fields

public/locales/en.json, src/views/credentials/viewCredentialsList.tsx, src/views/scans/viewScansList.tsx, src/views/sources/viewSourcesList.tsx
Unify popup style across Sources, Creds, Scans
Remove cancel button
- fix to "[Mirek] On “Sources” list. I can click a number in “Credentials” column and that will open new popup window. That window has both “close” button and “cancel” link (all lowercase). “close” is with red background, as if that was destructive action. That popup should probably use the same style as “Last connected” popup - it is purely informative.
The same applies to popup that appears on “Credentials” page, when clicking number in “Sources” column
It also appears on “Scans” page, when clicking number in “Sources” column"
1. confirm connections display …
=> style(cred,source,scan): ds-438  popup style fix

src/helpers/__tests__/__snapshots__/helpers.test.ts.snap, src/helpers/__tests__/helpers.test.ts, src/helpers/helpers.ts, src/types/types.ts
Utilize newly added auth_type field sent by the API instead of inferring it in the front end 
- [Related server side PR ](https://github.com/quipucords/quipucords/pull/2735)
- fix to "[Brad] If you start by running the old UI, create a network credential in the old UI using an SSH key (file path), and then start running the new UI, the credentials page crashes and turns completely blank.
2024-09-18 In progress PR
Old behavior: You can see all credentials.
Expected behavior: You can see all credentials that were created with the old UI in the new UI.
Current behavior: The credentials page crashes and shows a completely blank page (no UI or HTML/DOM at all).
[Slack thread with details](https://redhat-internal.slack.com/archives/C02QSNF1UKE/p1726001863082449?thread_ts=1726001806.711239&cid=C0 …
=> fix(credential):ds-438 use auth_type sent from api

src/views/credentials/viewCredentialsList.tsx
Removed variant from table battery component that was the responsible for causing inconsistencies in padding across views. 
- fix "[Mirek] Top margin in page content (below black header) is smaller on Credentials than it is on Sources and Scans"
[DISCOVERY-438](https://issues.redhat.com/browse/DISCOVERY-438)
=> style(credentials): ds-438 fix inconsistent style

src/hooks/__tests__/__snapshots__/useLoginApi.test.ts.snap, src/hooks/__tests__/useLoginApi.test.ts, src/hooks/useLoginApi.ts, tests/__snapshots__/code.test.ts.snap
- fix: ds-356 axios response interceptors
- assumed patch for token deletion, or random, 401s. this is an incremental change
- alerting users to 4xx level errors for login, similar to v1.8 is outside of this patch and possibly requires altering the current view component layout
- patching 4xx level errors with a login display message is outside of this patch
- patching 5xx level errors with a display message possibly requires alteration of current view base `get`s and is ignored with this patch
1. confirm linting and tests come back as expected
1. `$ npm run start:stage` or your equivalent use of tooling for previous determination of errors
1. attempt to generate a 401 for any …
=> fix: ds-356 axios response interceptors

public/locales/en.json, src/views/credentials/viewCredentialsList.tsx, src/views/sources/viewSourcesList.tsx
Follow consistent pattern in displaying credentials and sources names. 
- fix "[Mirek] On Credentials page, when filtering by Credential Type, items in dropdown use different labels than “Type” column in a table:
Filter says “vCenter”, but table says “vCenter Server”
Filter says “Ansible”, but table says “Ansible Controller”
Other labels are consistent
The same applies to Sources page and Source Type
[Mirek] On Credentials page, when filtering by Credential Type, items in dropdown are sorted alphabetically. But when clicking “Add Credentials”, the same set of items is sorted in arbitrary order (Network on top, Ansible last). They probably should be consistent
The same applies to Sources page and Source Type filter"
1. confirm …
=> fix(creds,sources): ds-438 names inconsistency

public/locales/en.json, src/components/login/__tests__/__snapshots__/login.test.tsx.snap, src/components/login/login.tsx, tests/__snapshots__/dist.test.ts.snap
- fix: ds-356 login loading, error messages
- error messaging for login was previously more integrated with the Django templates. moving to the token service does not provide the same level of error messages
- went ahead and provide the immediate response for 400, bad request, level status since that's what's provided by the API error response
- this starts the process of applying error codes, via status codes, to UI locale strings
1. confirm tests now come back clean
1. `$ npm run start:stage`
1. confirm login error messages attempt to display on the login
[DISCOVERY-356](https://issues.redhat.com/browse/DISCOVERY-356)
=> fix: ds-356 login loading, error messages

src/components/typeAheadCheckboxes/typeaheadCheckboxes.tsx, src/views/sources/__tests__/__snapshots__/addSourceModal.test.tsx.snap, src/views/sources/__tests__/addSourceModal.test.tsx, src/views/sources/addSourceModal.tsx, src/views/sources/viewSourcesList.tsx, tests/__snapshots__/code.test.ts.snap
Align form state with credential form in order to maintain consistency, but also to solve some of the state problems we are currently experiencing in the modal. 
- fix to [Mirek] New source popup remembers credentials and “Verify SSL Certificate” state across closing and opening
easy way to reproduce: start creating a new source of any type. Select some credentials. Close the popup (Esc key or Cancel link). Now start creating a new source of different type. Credentials field will say that you have some credentials selected, but since they are of different type, they won’t appear on the list. If you try to submit form now, server will return error
- [Mirek] New OpenShift source modal. Credentials dropdown is multi-select, but if I try to submit OpenShift with many credentials, server will …
=> refactor(addSourceModal): align form state with credential form

public/locales/en.json
Mirek noticed both authorization and authentication type being used in different places to refer to credentials. We agreed Authentication type  was the right word to be used. 
- fix to [Mirek] Credential page has column “Authorization type”, but add credential modal has the same field labeled “Authentication Type”. Both should use the same word.
In Slack thread ([link](https://redhat-internal.slack.com/archives/C02QSNF1UKE/p1726840763284999)) we agree that correct word is “Authentication”, so column name should change
[DISCOVERY-438](https://issues.redhat.com/browse/DISCOVERY-438)
=> fix(creds): ds-438 use consistent naming

src/views/scans/showScansModal.tsx, src/views/scans/viewScansList.tsx, tests/__snapshots__/code.test.ts.snap
Add close button to last-scanned modal to keep consistency with all other modals. 
- fix to [Mirek] “Last Scanned” modal does not have “Close” link/button at the bottom. Every other modal has it (create credential / source, Last connected in Sources, Credentials / Sources modal - but see above). For consistency, that one should have it as well.
[DISCOVERY-437](https://issues.redhat.com/browse/DISCOVERY-437)
=> feat(scans): ds-437 add close button to modal

src/views/sources/__tests__/__snapshots__/addSourceModal.test.tsx.snap, src/views/sources/__tests__/addSourceModal.test.tsx, src/views/sources/addSourceModal.tsx, tests/__snapshots__/code.test.ts.snap
Add conditional default port for OpenShift in form logic
- fix to [mirek] improve port logic on sources:
[check for mirek comment](https://github.com/quipucords/quipucords-ui/pull/460)
default ports: 22 network / 6443 openshift / 443 rest
[DISCOVERY-436](https://issues.redhat.com/browse/DISCOVERY-436)
=> fix: ds-436 Add OCP default port in form logic

src/views/scans/viewScansList.tsx, src/views/sources/viewSourcesList.tsx
- Add source name filter to scans view
- Fix credential by name filter text in sources view
- fix to  [Mirek] In Scans page, it is not possible to filter scans by source name. In old UI I could filter by “Name” or “Source
- fix to  [Mirek] Sources page. In filters, select “Credential name”. The input placeholder says “Filter by credential type” (should be “by credential name”)
[DISCOVERY-437](https://issues.redhat.com/browse/DISCOVERY-437)
[DISCOVERY-436](https://issues.redhat.com/browse/DISCOVERY-436)
=> Add source name filter to scans view

public/locales/en.json, src/components/aboutModal/__tests__/__snapshots__/aboutModal.test.tsx.snap, src/components/aboutModal/__tests__/aboutModal.test.tsx, src/components/aboutModal/aboutModal.tsx, src/components/viewLayout/__tests__/__snapshots__/viewLayoutToolbar.test.tsx.snap, src/components/viewLayout/__tests__/viewLayout.test.tsx, src/components/viewLayout/viewLayout.tsx, src/components/viewLayout/viewLayoutToolbar.tsx, src/helpers/__tests__/__snapshots__/helpers.test.ts.snap, src/helpers/__tests__/helpers.test.ts, src/helpers/helpers.ts, src/hooks/__tests__/__snapshots__/useStatusApi.test.ts.snap, src/hooks/__tests__/useStatusApi.test.ts, src/hooks/useStatusApi.ts, tests/__snapshots__/code.test.ts.snap
- feat(aboutModal): ds-808 display user, status info
* aboutModal, display user and status info
* viewLayout, use title image helper
* viewLayoutToolbar, add about modal open, close
* helpers, add ui_version, getCurrentDate, getTitleImg
* useStatusApi, use status api response
- modifies the brand image into a centralized helper to avoid recreating the logic in multiple places
- adds the centralized `getCurrentDate` and `UI_VERSION` helpers from `v1.8`
- what this doesn't do (these items can be iterated on if necessary)
- ~skips adding the UI browser type from `v1.8` since it involves adding in one more NPM.~
- skips the `v1.8` custom copy/paste behavior.
- running locally
- the randomized data local run using `$ npm start` (generated from the `spec` file) returns a `500` level error from …
=> feat(aboutModal): ds-808 display user, status info

src/views/credentials/viewCredentialsList.tsx, src/views/scans/viewScansList.tsx, src/views/sources/viewSourcesList.tsx
Display list of sources and credentials in alphabetical order
- fix to [Mirek] A list of Sources used by a credential, or sources used by a scan (the one that appears in modal) is sorted by related items id. It would be more natural to sort it alphabetically.
Not tested, but I assume the same applies to list of credentials used by a source
[DISCOVERY-438](https://issues.redhat.com/browse/DISCOVERY-438)
=> refactor: ds-438 display items alphabetical order

src/components/typeAheadCheckboxes/typeaheadCheckboxes.tsx
New useEffect: The useEffect that syncs the internal selected state with the selectedOptions prop ensures that when the selectedOptions prop changes (such as when editing a source), the dropdown reflects the correct pre-selected credentials.
- fix to [Mirek] When editing a source, “Credentials” field say “0 items selected”. Looks like credentials are not correctly associated with existing source in the list component.
if I edit a source and select new credentials, and then save, these new credentials will be selected when I edit the source again. So this affects only editing after create
1. confirm connections display as …
=> Fix creds in edit source

src/helpers/__tests__/helpers.test.ts, src/helpers/helpers.ts, src/views/sources/__tests__/__snapshots__/addSourceModal.test.tsx.snap, src/views/sources/addSourceModal.tsx
Allow user to delimit hosts (hostnames, IP addresses or IP ranges) by space or newline, in addition to comma. This brings new UI in line with old UI, which allowed wider range of user values and transformed them automatically before submitting to backend.
Relates to JIRA: DISCOVERY-503
Questions / points for discussion:
* Should we also have client-side validation of values? Backend rules for what counts as valid host address are [somewhat complex](https://github.com/quipucords/quipucords/blob/main/quipucords/api/source/serializer.py#L276) and I don't really want to repeat them here, but we can definitely fail early for things that are obviously wrong - empty values, invalid host names, multiple hosts where only one should be applied.
* This function is applied when submitting a form and …
=> fix(sources): ds-503 accept wider range of hosts values

src/views/scans/useScansQuery.ts
[Scans sorting field is called `most_recent_scanjob__start_time`](https://github.com/quipucords/quipucords/blob/main/quipucords/api/scan/view.py#L261). `most_recent_connect_scan__start_time` is available only in sources API.
We even have that string in constants, but it is unused. I looked into git history and it seems that this mistake was introduced back during PF4 migration. Probably a mis-click when selecting a value from intellisense list.
I tested locally that with that patch, clicking headers in scans list changes the order of items. Let me know if there are more places I should change.
=> fix: ds-441 use correct API field when sorting scans

src/views/sources/viewSourcesList.tsx, tests/__snapshots__/code.test.ts.snap
- fix(viewSourcesList): ds-813 useShowConnectionsApi catch errors
- applies a catch similar to the `addSourceModal` implementation of `getCredentials`
1. `$ npm run start:stage`
1. you can attempt to emulate the behavior of what the display will look like on failure either
- by mocking an error for the API call
- or more directly by putting the same value used for the error inside the success callback, temporarily
You should see a result similar to the example below on failure
[DISCOVERY-813](https://issues.redhat.com/browse/DISCOVERY-813)
=> fix(viewSourcesList): ds-813 useShowConnectionsApi catch errors

package-lock.json, package.json
- build(deps): lock reset, update weldable from 3.1.3 to 3.2.0
- lock reset included to help bump deps
1. `$ npm run build`
...
ongoing
=> build(deps): lock reset, update weldable from 3.1.3 to 3.2.0

src/views/scans/showScansModal.tsx
Scan Download button is displayed when scan has report_id field. However, report_id is assigned as soon as scan finished running, but before fingerprinting phase has finished. And it is not possible to download a scan before fingerprinting phase finished.
Arguably this is API not playing very nice, but it's trivial for UI to wait for end_time field. That field is only present on scans that are all completed and reports can be downloaded.
Also, fix typing warning in the same file.
Relates to JIRA: DISCOVERY-531
=> fix(scans) ds-531 Stop showing download button too soon

public/locales/en.json, src/views/sources/viewSourcesList.tsx
Fixes a minor issue from the doc:
> Sources [Mirek] Sources page may display empty cell in “Last connected” column.
> * Steps: Create a source. Click “Scan” to scan it. Wait for scan to finish and go to “Scans”. Find that scan and remove it. Go back to “Sources” page.
This also happens if you create a source using CLI or API directly, where you can opt-out of initial scan.
I'm happy to take suggestions how phrasing can be improved.
Not a huge fan of how this text is misaligned compared to text displayed when scan is running or finished (see screenshot). But for "scan-ful" sources text is displayed inside `<Button>`, which adds left padding, and as far as I can tell, we can't have "transparent" buttons (i.e. apply all the paddings, but none of text formatting). Given that most of users are …
=> fix(sources): ds-436 display message if scan has not run yet

src/components/login/login.tsx
extractErrorMessage helper expects response body data, not generic AxiosError.
I tried, and failed, to check what kind of error message would be displayed if something happens to session while you are logged in. I'm happy to take pointers to other places similar change should be made.
Error message on bad credentials (this one comes from [locale file](https://github.com/quipucords/quipucords-ui/blob/main/public/locales/en.json#L135)):
Error message after providing bad credentials too many times (this one comes from backend):
Relates to JIRA: DISCOVERY-805
=> feat(login): ds-805 Display proper message on 403 response

src/components/contextIcon/contextIcon.tsx, src/views/scans/viewScansList.tsx
If the scan has been created but not run yet, don't make "Scan created" cell in table a link. This prevents `<ShowScansModal>` from appearing. Modal would contain empty table.
Also changed icon from unknown to off. [Patternfly icon library](https://www.patternfly.org/design-foundations/icons/) says it "Represents status: powered off", which seems exactly what we have here.
Unfortunately, it has the same mis-alignment issue as #497 . Fortunately, most users will never see this.
This fixes following two issues from docs:
> Scan objects that were never scanned (duh) still have clickable “Scan created” in Last scanned column. The modal displays empty table
> [Mirek] Scans page. In “Last scanned” column, there’s no space between icon and text. Very similar to issue that Bruno reported for …
=> fix(scans): ds-437 Prevent empty modal

src/views/scans/__tests__/__snapshots__/showScansModal.test.tsx.snap, src/views/scans/__tests__/showScansModal.test.tsx, src/views/scans/showScansModal.tsx
Fix sorting mechanism in "Last Scanned" modal headers. 
- fix to  [Mirek] “Last Scanned” modal. Clicking table header items inside modal does not actually change the order of items in table.
- This PR does not include pagination. If the number of scan jobs exceeds the visible screen area, you will need to scroll down to view all of them. However, sorting is applied across the entire list of scan jobs.
[DISCOVERY-437](https://issues.redhat.com/browse/DISCOVERY-437)
=> fix(showScansModal): ds-437 sort last scanned headers

src/helpers/__tests__/helpers.test.ts, src/helpers/helpers.ts, src/views/sources/addSourceModal.tsx, src/views/sources/addSourcesScanModal.tsx
I noticed that search directories textarea ("deep scan") has the same problem as hosts textarea. We fixed hosts in #475 (b1909a77b458f8be618dea023519fce1611a1230), now it's time to fix that one.
As far as I can tell, there are no other fields that would take comma-separated list of values.
I decided to rename `normalizeHosts` helper into something more generic and re-use that. This will conflict badly with #492 . I guess the alternative is to have internal helper `normalizeCommaSeparated` and public-facing `normalizeHosts` and `normalizeSearchDirs`. Not sure which solution is more aligned with current code practices.
=> fix(sources): ds-436 accept wider range of directories values

src/views/sources/viewSourcesList.tsx, tests/__snapshots__/code.test.ts.snap
This is followup to fd447c501c5a4852f581ee2e81b41e8adfb3485f (#497). After that commit, "Scan not started" message was not aligned with other statuses. Now message is wrapped in disabled Button and has an icon, making a look more consistent.
Relates to JIRA: DISCOVERY-436
=> fix(sources): ds-436 wrap scan not run message in Button

src/views/credentials/viewCredentialsList.tsx, src/views/scans/viewScansList.tsx, src/views/sources/viewSourcesList.tsx, tests/__snapshots__/code.test.ts.snap
Selecting multiple items and deleting them kept them selected in state, which could result in failures of subsequent operations - especially creating scans (because scan would try to involve sources that no longer exist).
Since bulk delete might result in deleting some items, but not the others, arguably these that were not deleted should still be selected. With current code they won't. But that seems like a relatively minor inconvenience at best.
Relates to JIRA: DISCOVERY-832
=> fix(views): ds-832 unselect items upon deletion

.github/workflows/build.yml
As discussed at standup with @ruda and the dev team on 2024-11-12.
=> build: bump quay.expires-after from 5d to 7d to allow more test time

public/locales/en.json, src/components/actionMenu/actionMenu.tsx, src/helpers/helpers.ts, src/types/types.ts, src/views/scans/__tests__/showScansModal.test.tsx, src/views/scans/showScansModal.tsx, src/views/scans/viewScansList.tsx
The button shall only be enabled when the scan is completed.
Includes a dropdown button on scan row kebab for downloading reports.
- The button should be disabled for failed or incomplete scans.
- If a "complete" scan doesn't have a `report_id` (due to a bug/edge-case on the backend?). a client-side error will be thrown
Kebab for scans ~in progress~ not ready for download
...and for completed ones
On download completion, an alert should be displayed. Same shall happen on errors, but that's harder to test without
monkey-patching the server
...
[DISCOVERY-347](https://issues.redhat.com/browse/DISCOVERY-347)
=> feat(ActionMenu<Scan>): ds-437 add download report button

src/hooks/__tests__/__snapshots__/useCredentialApi.test.ts.snap, src/hooks/__tests__/__snapshots__/useScanApi.test.ts.snap, src/hooks/__tests__/__snapshots__/useSourceApi.test.ts.snap, src/hooks/__tests__/useCredentialApi.test.ts, src/hooks/__tests__/useScanApi.test.ts, src/hooks/__tests__/useSourceApi.test.ts, src/hooks/useCredentialApi.ts, src/hooks/useScanApi.ts, src/hooks/useSourceApi.ts, src/views/credentials/viewCredentialsList.tsx, src/views/sources/viewSourcesList.tsx, tests/__snapshots__/code.test.ts.snap
- fix: ds-839 block modal form submissions
- leverages existing toast notification layout to aid in preventing modal closing after form submission
- basic blocking for modal forms for
- Add/Edit source api hooks
- Add scan api hooks
- Add/Edit credential api hooks
- Technically the Edit aspect is still being worked on under #428  this simply adds the `Promise.reject` when ready
- what this doesn't do
- enhance the toast notification messages or perform inline form messaging.
- give some level of loading indicator for the form submission
1. `$ npm run start:stage`
1. confirm basic form submission for 
- Add/Edit sources is blocked with a toast notification
- Adding a scan is blocked with a toast notification
- Adding a credential is blocked …
=> fix: ds-839 block modal form submissions

.github/workflows/build.yml
It doesn't make sense for frontend / app container to have a "quipucords.backend" label in container image.
Relates to JIRA: DISCOVERY-748
=> chore(build): ds-748 use correct container label

src/components/actionMenu/__tests__/__snapshots__/actionMenu.test.tsx.snap, src/components/actionMenu/actionMenu.tsx, src/views/scans/showScansModal.tsx, src/views/scans/viewScansList.tsx
SSIA - add a bunch of `ouiaId` attributes to make it easier for Camayoc to test flows around downloading reports.
=> test: add ouiaId to make reports downloading easier

package.json
`npm run start:using-server` will serve the development UI properly wired to a running instance of quipucords server. Default configuration points to quipucords-installer defaults, and can be customized with QUIPUCORDS_SERVER_* variables.
=> chore: add a utility script to make development easier

.tekton/discovery-ui-pull-request.yaml, .tekton/discovery-ui-push.yaml, .tekton/downstream-build-arguments.conf, Containerfile
konflux configuration adjusted to have all required checks passing on Red Hat Enterprise Contract.
With these changes, the same `Containerfile` can be used for upstream and downstream builds.
make sure both konflux checks in this PR are passing.
~~export IMAGE=$(kubectl get component discovery-ui -o json | jq '.status.lastPromotedImage' -r)~~
```
export IMAGE="quay.io/redhat-user-workloads/discovery-tenant/discovery/discovery-ui:on-pr-$(git log --format="%H" -1)"
kubectl get secret imagerepository-for-discovery-ui-image-pull -o json | jq '.data[] | @base64d | fromjson | {auths: (.auths // .)}' > /tmp/auth.json
podman pull ${IMAGE} --authfile /tmp/auth.json 
podman run -p 9999:9999 -e QUIPUCORDS_APP_PORT=9999 -e QUIPUCORDS_SERVER_URL:-host.containers.internal:9443 -it $IMAGE
```
... …
=> ci: configure konflux build 

Containerfile
Lock base image by digest for reproducibility. This will also allow konflux to automatically open PRs updating the base images (through renovate/mintmaker).
Relates to JIRA: DISCOVERY-708
Use the image built by konflux: 
```
quay.io/redhat-user-workloads/discovery-tenant/discovery/discovery-ui:on-pr-$(git log --format="%H" -1)
```
[DISCOVERY-708](https://issues.redhat.com/browse/DISCOVERY-708)
=> build(konflux): lock base image by digest

.tekton/discovery-ui-pull-request.yaml, .tekton/discovery-ui-push.yaml
A bug caused an update from konflux to remove this info.
=> konflux: fix broken EC checks

.tekton/discovery-ui-push.yaml, package.json
Makes snyk results on "push" pipeline to be available on our org snyk dashboard.
This was inspired on @abellotti work on RedHatInsights/rhproxy-engine#75. One thing I chose to do differently
was to only enable this behavior on the "push" pipeline, as adding results from PRs could add too much noise
and confuse us (what would we see on snyk would be reflecting the current state of main or some change proposed in a PR?).
=> ci(konflux): make snyk results available on ui

src/hooks/__tests__/__snapshots__/useSourceApi.test.ts.snap, src/hooks/useSourceApi.ts
Relates to JIRA: DISCOVERY-784
This is the UI change that corresponds with this API change: https://github.com/quipucords/quipucords/pull/2812
=> refactor: creating a Source should not create a connect-type ScanJob

.github/workflows/integration.yml, .github/workflows/package_audit.yml, Containerfile, README.md, package-lock.json, package.json
Node 18 support shall end in the next 2 months. We need to migrate.
We could move to version 20, but considering 22 is also a LTS version and its EOL is set to 2027, let's try that.
[DISCOVERY-901](https://issues.redhat.com/browse/DISCOVERY-901)
=> build: move to node 22

.tekton/discovery-ui-pull-request.yaml, .tekton/discovery-ui-push.yaml
sast-unicode-check was not using the correct task since 5844e0069f0cbf8a34c756a170593671ba4eba08.
=> ci(konflux): add sast-unicode-check task

.tekton/discovery-ui-pull-request.yaml, .tekton/discovery-ui-push.yaml, .tekton/task/generate-version-labels.yaml
~~Add a make target to bump quipucords-ui version~~
Dynamically set "version" (X.Y.Z) and "version_minor" (X.Y) labels based on the version set on `package.json`.
The labels added on Containerfile match the tags proposed for use on the `ReleasePlanAdmission` .
See https://url.corp.redhat.com/473b3be.
=> ci(konflux): dynamically set version labels

public/locales/en.json, src/views/scans/viewScansList.tsx
Scan removal confirmation dialog should refer to "scan", not "source".
There was already a string for dialog body, but it was unused. That string contained `<0>` `</0>`, which I assume should be HTML elements to wrap scan name - but they were printed verbatim by UI. Also, neither credential nor source wraps their name in element, so there's consistency in not using it in scan.
Relates to JIRA: DISCOVERY-891
=> fix(scans): dsc-891 Use "scan" in scan removal dialog

public/locales/en.json, src/components/aboutModal/__tests__/__snapshots__/aboutModal.test.tsx.snap, src/components/aboutModal/__tests__/aboutModal.test.tsx, src/components/aboutModal/aboutModal.tsx, src/hooks/useStatusApi.ts, tests/__snapshots__/code.test.ts.snap
Add CPU Architecture field to "About" dialog. Data is already provided by a server. I decided to use [`platform.machine()`](https://docs.python.org/3/library/platform.html#platform.machine), the alternative being [`platform.processor()`](https://docs.python.org/3/library/platform.html#platform.processor). On upstream container both provide the same value, while on my local Python running on bare metal `processor()` is empty string.
I guess technically backend container might be using different arch than frontend container, but we don't support setups like that.
Relates to JIRA: DISCOVERY-857
=> feat(about): dsc-857 show CPU architecture

.github/workflows/build.yml
build: preferring to use buildah to create multi-arch images.
- Preferring to use our own buildah github action for creating the multi-arch manifests.
=> build: Use buildah for multi arch manifests

.github/workflows/build.yml
See also this PR for quipucords:
https://github.com/quipucords/quipucords/pull/2931
See this conversation for context:
https://redhat-internal.slack.com/archives/C02QSNF1UKE/p1746208791358419
TLDR: I discovered that we are pushing the combined manifest for `latest` but not for `main`, `latest` basically aliases the `main` tag, and nothing we know currently uses `main`. So, drop `main` and keep `latest`.
=> build: stop pushing `main` container tags (but continue pushing `latest`)

.tekton/discovery-ui-pull-request.yaml, .tekton/discovery-ui-push.yaml, .tekton/task/generate-version-labels.yaml, CHANGELOG.md, Containerfile, package-lock.json, package.json
- backport the fix implemented in quipucords/quipucords#2933
- refresh locks (excluding npm lock)
- bump to 1.14.1
=> chore: bump to 1.14.1, refresh locks and add check for invalid version labels

.tekton/discovery-ui-pull-request.yaml, .tekton/discovery-ui-push.yaml
Relates to JIRA: DISCOVERY-969
Worflow for tagging and opening PR against other branches was tested on yaka repo.
=> ci(konflux): adjust pipeline to support discovery release workflow

src/components/typeAheadCheckboxes/typeaheadCheckboxes.tsx, src/views/sources/viewSourcesList.tsx, tests/__snapshots__/code.test.ts.snap
Add missing ouiaId to source kebab, to make editing sources easier.
Also fix ouiaId of typeAheadCheckboxes "clear" element.
Relates to JIRA: DISCOVERY-983
=> Add/fix ouiaId for source kebab and typeAheadCheckboxes

src/components/viewLayout/viewLayoutToolbar.tsx
The change is requested in DISCOVERY-1098 , but let's decouple it from overview page, which will take longer to merge.
Relates to JIRA: DISCOVERY-1098
=> view(toolbar): Switch icon on top
